from django.conf.urls import include, url
#from filebrowser.sites import site
import nested_admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^neu/$', views.neu, name='neu'),
    url(r'^zustiege/$', views.zustiege, name='zustiege'),
    url(r'^zubringer/$', views.zubringer, name='zubringer'),
    url(r'^ablauf/$', views.ablauf, name='ablauf'),
    url(r'^printZubringer/$', views.printZubringer, name='printZubringer'),
    url(r'^aktuelleReisen/$', views.aktuelleReisen, name='aktuelleReisen'),
    #url(r'^winter2016_17/$', views.winter2016_17, name='winter2016_17'),
    url(r'^winter2017_18/$', views.winter2017_18, name='winter2017_18'),
    url(r'^rb24/$', views.rb24, name='rb24'),
    url(r'^winter2018_19/$', views.winter2018_19, name='winter2018_19'),
    #url(r'^winter1617/$', views.winter1617, name='winter1617'),
    url(r'^winter1718/$', views.winter1718, name='winter1718'),
    url(r'^winter1819/$', views.winter1920, name='winter1920'),
    url(r'^winter1920/$', views.winter1920, name='winter1920'),
    url(r'^winter2021/$', views.winter2021, name='winter2021'),
    url(r'^winter2122/$', views.winter2122, name='winter2122'),
    url(r'^winter2223/$', views.winter2223, name='winter2223'),
    url(r'^winter2324/$', views.winter2324, name='winter2324'),
    url(r'^winter2425/$', views.winter2425, name='winter2425'),
    url(r'^sommer17/$', views.sommer17, name='sommer17'),
    url(r'^sommer18/$', views.sommer18, name='sommer18'),
    url(r'^sommer19/$', views.sommer19, name='sommer19'),
    url(r'^sommer20/$', views.sommer20, name='sommer20'),
    url(r'^sommer21/$', views.sommer21, name='sommer21'),
    url(r'^sommer22/$', views.sommer22, name='sommer22'),
    url(r'^sommer23/$', views.sommer23, name='sommer23'),
    url(r'^sommer24/$', views.sommer24, name='sommer24'),
    url(r'^sommer25/$', views.sommer24, name='sommer25'),
    url(r'^tagesfahrten/$', views.tagesfahrten, name='tagesfahrten'),
    url(r'^winter2016_17_export/$', views.winter2016_17_export, name='winter2016_17_export'),
    url(r'^reiseterminuebersicht/$', views.reiseterminuebersicht, name='reiseterminuebersicht'),
    url(r'^reiseuebersichtwinter/$', views.reiseuebersichtwinter, name='reiseuebersichtwinter'),
    url(r'^reisezieluebersicht/$', views.reisezieluebersicht, name='reisezieluebersicht'),
    url(r'^reise_detail_export/(?P<pk>[-\w]+)/$', views.reise_detail_export, name='reise_detail_export'),
    url(r'^reise_detail_export_alles/(?P<pk>[-\w]+)/$', views.reise_detail_export_alles, name='reise_detail_export_alles'),
    url(r'^reise/(?P<pk>[\w]+)/$', views.reise_detail, name='reise_detail'),
    url(r'^reise/(?P<slug>[-_\w]+)/', views.reise_detail, name='reise_detail'),
    url(r'^reise/(?P<slug>[-_\w]+),(?P<pk>[\w]+)/', views.reise_detail, name='reise_detail'),
#    url(r'^reise/winter1617/(?P<pk>[\w]+)/$', views.reise_detail, name='reise_detail_web_alt'),
#    url(r'^reise/winter1617(?P<slug>[-_\w]+)/', views.reise_detail, name='reise_detail_web_alt'),
    #url(r'^admin/filebrowser/', include(site.urls)),
    #url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^nested_admin/', include('nested_admin.urls')),
]
