# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reise',
            fields=[
                ('reiseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=b'', help_text=b'Geben Sie hier einen evtl. abweichenden URL-String ein.')),
                ('reisetyp', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier den Typ der Reise ein. (max. 30 Zeichen) (Kann evtl. automatisch gef\xc3\xbcllt werden.)', max_length=60, verbose_name=b'Reisetyp')),
                ('titel', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier den Titel der Reise ein. (max. 60 Zeichen)', max_length=128, verbose_name=b'Reisetitel')),
                ('untertitel', models.CharField(blank=True, default=b'', max_length=128, verbose_name=b'Reiseuntertitel (etwa 40-70 Zeichen)')),
                ('einleitung', models.TextField(blank=True, default=b'', verbose_name=b'Reise Zusammenfassungstext (etwa 300-550 Zeichen)')),
                ('datum_erzeugung', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Erzeugungsdatum')),
                ('zuletzt_bearbeitet', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_veroeffentlichung', models.DateTimeField(blank=True, null=True, verbose_name=b'Ver\xc3\xb6ffentlichungsdatum')),
                ('datum_verfall', models.DateTimeField(blank=True, null=True, verbose_name=b'Verfallsdatum')),
                ('katalogseite', models.IntegerField(null=True, verbose_name=b'Katalogseite')),
                ('anzahl_seiten_im_katalog', models.IntegerField(null=True, verbose_name=b'Anzahl der Seiten f\xc3\xbcr diese Reise im Katalog')),
                ('leistungen_kommentar', models.CharField(blank=True, default=b'', max_length=128, verbose_name=b'Kommentar zu Leistungen, falls n\xc3\xb6tig. (etwa 40-70 Zeichen)')),
                ('zusatzleistungen_titel', models.CharField(blank=True, default=b'', max_length=128, verbose_name=b'Titelzeile f\xc3\xbcr zus\xc3\xa4tzliche Leistungen, falls n\xc3\xb6tig. (etwa 40-70 Zeichen)')),
                ('zusatzleistungen_kommentar', models.CharField(blank=True, default=b'', max_length=128, verbose_name=b'Kommentar f\xc3\xbcr zus\xc3\xa4tzliche Leistungen, falls n\xc3\xb6tig. (etwa 40-70 Zeichen)')),
                ('korrektur_bemerkung_intern', models.TextField(blank=True, default=b'', help_text=b'Wird nur intern dargestellt und dient Notizen die Reise betreffend, Korrekturbemerkungen, etc.', verbose_name=b'Korrekturfeld')),
                ('zubucher', models.CharField(blank=True, default=b'', max_length=128, verbose_name=b'Text Zubucherreise, falls n\xc3\xb6tig. (etwa 40-70 Zeichen)')),
                ('autor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reisen', to=settings.AUTH_USER_MODEL)),
                ('zuletzt_bearbeitet_von', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reisen_bearbeiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reise',
                'verbose_name_plural': 'Reisen',
            },
        ),
        migrations.CreateModel(
            name='Reisetage',
            fields=[
                ('reisetagID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tagnummer', models.IntegerField(null=True, verbose_name=b'Tagesnummer zum Ordnen')),
                ('titel', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier den Titel der Tagesbeschreibung ein. (max. 70 Zeichen)', max_length=128, verbose_name=b'Titel Tagesbeschreibung')),
                ('beschreibung', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier Tagesbeschreibung ein. (Die max. Anzahl Zeichen ist abh\xc3\xa4ngig von Anzahl der Tage und Bilder je Reise etc. (etwa800))', verbose_name=b'Beschreibung Tag')),
                ('zusatz', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier zus\xc3\xa4tzliche Informationen zur Tagesbeschreibung ein. (Tipps, etc.)', verbose_name=b'Zusatz zur Tagesbeschreibung')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Reisetag',
                'verbose_name_plural': 'Reisetage',
            },
        ),
        migrations.CreateModel(
            name='Reisetermine',
            fields=[
                ('reiseterminID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('markierung', models.CharField(blank=True, help_text=b'Markierung f\xc3\xbcr evt. Spezialtermine (*)', max_length=20, verbose_name=b'Markierung')),
                ('kommentar', models.CharField(blank=True, help_text=b'Kommentar/Hinweise', max_length=20, verbose_name=b'Kommentar')),
                ('datum_beginn', models.DateField(blank=True, default=b'', verbose_name=b'Reisebeginn')),
                ('datum_ende', models.DateField(blank=True, default=b'', null=True, verbose_name=b'Reiseende')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Reisetermin',
                'verbose_name_plural': 'Reisetermine',
            },
        ),
    ]
