# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeistungenReise',
            fields=[
                ('leistung_reiseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leistung', models.CharField(blank=True, help_text=b'einzelne Leistung zur Reise', max_length=128, verbose_name=b'Leistung')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Leistung bei der Darstellung', null=True, verbose_name=b'position')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Reiseleistung',
                'verbose_name_plural': 'Reiseleistungen',
            },
        ),
    ]
