# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0002_leistungenreise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruehbucherrabatt',
            fields=[
                ('fruehbucherrabattID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datum_bis', models.DateField(blank=True, default=b'', verbose_name=b'Datum G\xc3\xbcltigkeit Fr\xc3\xbchbucherrabatt')),
                ('rabatt', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'Rabatt')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Leistung bei der Darstellung', null=True, verbose_name=b'position')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Fr\xfchbucherrabatt',
                'verbose_name_plural': 'Fr\xfchbucherrabatte',
            },
        ),
    ]
