# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0003_fruehbucherrabatt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zusatzleistung',
            fields=[
                ('zusatzleistungID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier die Zusatzleistung ein.', verbose_name=b'Zusatzleistung')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'Preis')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Leistung bei der Darstellung', null=True, verbose_name=b'position')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Zusatzleistung',
                'verbose_name_plural': 'Zusatzleistungen',
            },
        ),
    ]
