# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0004_zusatzleistung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hinweis',
            fields=[
                ('hinweisID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hinweis', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier den Hinweis ein.', verbose_name=b'Hinweis')),
            ],
            options={
                'verbose_name': 'Hinweis',
                'verbose_name_plural': 'Hinweise',
            },
        ),
        migrations.CreateModel(
            name='Reisehinweise',
            fields=[
                ('reisehinweiseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier die Reisehinweise ein.', verbose_name=b'Reisehinweis')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Reisehinweise bei der Darstellung', null=True, verbose_name=b'position')),
                ('hinweis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Hinweis')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Reisehinweis',
                'verbose_name_plural': 'Reisehinweise',
            },
        ),
        migrations.AddField(
            model_name='reise',
            name='hinweise',
            field=models.ManyToManyField(through='reisen.Reisehinweise', to='reisen.Hinweis'),
        ),
    ]
