# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0005_auto_20160115_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reise',
            name='anzahl_seiten_im_katalog',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Anzahl der Seiten f\xc3\xbcr diese Reise im Katalog'),
        ),
        migrations.AlterField(
            model_name='reise',
            name='katalogseite',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Katalogseite'),
        ),
        migrations.AlterField(
            model_name='reisehinweise',
            name='titel',
            field=models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier einen optionalen Titel ein.', verbose_name=b'optionaler Titel'),
        ),
        migrations.AlterField(
            model_name='reisetage',
            name='tagnummer',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Tagesnummer zum Ordnen'),
        ),
    ]
