# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0006_auto_20160115_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('kategorieID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kategorie', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier die Kategorie ein.', verbose_name=b'Kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Reisekategorien',
            fields=[
                ('reisekategorienID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Kategorien bei der Darstellung', null=True, verbose_name=b'Position')),
                ('kategorie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Kategorie')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Reisekategorie',
                'verbose_name_plural': 'Reisekategorien',
            },
        ),
    ]
