# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0007_kategorie_reisekategorien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reisezielregionen',
            fields=[
                ('reisezielregionenID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Zielregionen bei der Darstellung', null=True, verbose_name=b'Position')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
                ('zielregion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Kategorie')),
            ],
            options={
                'verbose_name': 'Zielregion',
                'verbose_name_plural': 'Zielregionen',
            },
        ),
        migrations.CreateModel(
            name='Zielregion',
            fields=[
                ('zielregionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier die Zielregion ein.', max_length=256, verbose_name=b'Zielregion')),
            ],
            options={
                'verbose_name': 'Zielregion',
                'verbose_name_plural': 'Zielregionen',
            },
        ),
    ]
