# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0008_reisezielregionen_zielregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reisezielregionen',
            name='zielregion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Zielregion'),
        ),
    ]
