# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0009_auto_20160115_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reise',
            name='hinweise',
        ),
    ]
