# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0010_remove_reise_hinweise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausflugspakete',
            fields=[
                ('ausflugspaketID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.CharField(blank=True, help_text=b'Hier den Titel des Ausflugspakets eingeben', max_length=256, verbose_name=b'Titel Ausflugspaket')),
                ('kommentar_titel', models.CharField(blank=True, help_text=b'Hier den Titelkommentar zum Ausflugspaket eingeben', max_length=256, verbose_name=b'Titelkommentar Ausflugspaket')),
                ('kommentar', models.CharField(blank=True, help_text=b'Hier den Kommentar zum Ausflugspaket eingeben', max_length=256, verbose_name=b'kommentar Ausflugspaket')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Leistung bei der Darstellung', null=True, verbose_name=b'position')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Ausflugspaket',
                'verbose_name_plural': 'Ausflugspakete',
            },
        ),
    ]
