# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0011_ausflugspakete'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeistungenAusflugspaket',
            fields=[
                ('leistung_ausflugspaketID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leistung', models.CharField(blank=True, help_text=b'Hier die Leistung zum Ausflugspaket eingeben', max_length=256, verbose_name=b'Leistung Ausflugspaket')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Leistung bei der Darstellung', null=True, verbose_name=b'position')),
                ('ausflugspaket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Leistung zum Ausflugspaket',
                'verbose_name_plural': 'Leistungen zum Ausflugspaket',
            },
        ),
    ]
