# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0012_leistungenausflugspaket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leistungenausflugspaket',
            name='ausflugspaket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Ausflugspakete'),
        ),
    ]
