# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0013_auto_20160115_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preis',
            fields=[
                ('preisID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier ein, was dann vorm Eurobetrag stehen soll.', max_length=256, verbose_name=b'Titel/Preisart')),
            ],
            options={
                'verbose_name': 'Preis',
                'verbose_name_plural': 'Preise',
            },
        ),
        migrations.CreateModel(
            name='Reisepreise',
            fields=[
                ('reisepreisID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'Preis')),
                ('kommentar', models.CharField(blank=True, help_text=b'Hier den Kommentar zum Ausflugspaket eingeben', max_length=256, verbose_name=b'kommentar Ausflugspaket')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Zielregionen bei der Darstellung', null=True, verbose_name=b'Position')),
                ('preis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Preis')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Reisepreis',
                'verbose_name_plural': 'Reisepreise',
            },
        ),
    ]
