# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0016_auto_20160116_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReisepreisZusatz',
            fields=[
                ('reisepreis_zusatzID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'Preisdetail')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Reisepreisdetails bei der Darstellung', null=True, verbose_name=b'Position')),
                ('preis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Preis')),
                ('reisepreis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reisepreise')),
            ],
            options={
                'verbose_name': 'Preisdetail',
                'verbose_name_plural': 'Preisdetails',
            },
        ),
    ]
