# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0017_reisepreiszusatz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausflugspaketpreise',
            fields=[
                ('ausflugspaketpreiseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'Preisdetail')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Ausflugspaketpreise bei der Darstellung', null=True, verbose_name=b'Position')),
                ('ausflugspaket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Ausflugspakete')),
                ('preis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Preis')),
            ],
            options={
                'verbose_name': 'Ausflugspaketpreis',
                'verbose_name_plural': 'Ausflugspaketpreise',
            },
        ),
    ]
