# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0018_ausflugspaketpreise'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusflugspaketeZuReisetagen',
            fields=[
                ('ausflugspakete_zu_reisetagenID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erscheint_in', models.CharField(blank=True, help_text=b'Bitte w\xc3\xa4hlen ob Titel oder Tagesbeschreibung', max_length=256, verbose_name=b'Erscheint in')),
                ('ausflugspaket_text', models.CharField(blank=True, help_text=b'Bitte Text zum Ausflugspaket eingeben.', max_length=256, verbose_name=b'Text Ausflugspaket')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Ausflugspakete bei der Darstellung', null=True, verbose_name=b'Position')),
                ('ausflugspaket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Ausflugspakete')),
                ('reisetag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reisetage')),
            ],
            options={
                'verbose_name': 'Ausflugspaket zu Reisetag',
                'verbose_name_plural': 'Ausflugspakete zu Reisetagen',
            },
        ),
    ]
