# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0019_ausflugspaketezureisetagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausflugspaketezureisetagen',
            options={'verbose_name': 'Zuordnung von Ausflugspaket zu Reisetag', 'verbose_name_plural': 'Zuordnung von Ausflugspaketen zu Reisetagen'},
        ),
        migrations.AlterField(
            model_name='reise',
            name='anzahl_seiten_im_katalog',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Anzahl der Seiten f\xc3\xbcr diese Reise im Katalog'),
        ),
        migrations.AlterField(
            model_name='reise',
            name='katalogseite',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Katalogseite'),
        ),
    ]
