# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0020_auto_20160116_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausflugspakete',
            name='gehoert_zu_reisetagen',
            field=models.ManyToManyField(through='reisen.AusflugspaketeZuReisetagen', to='reisen.Reisetage'),
        ),
    ]
