# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0021_ausflugspakete_gehoert_zu_reisetagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reise',
            name='hinweise',
            field=models.ManyToManyField(through='reisen.Reisehinweise', to='reisen.Hinweis'),
        ),
    ]
