# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0022_reise_hinweise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('bildID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bild', models.ImageField(upload_to=b'images')),
                ('titel', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier den Titel des Bildes ein.', max_length=256, verbose_name=b'Bildtitel')),
                ('beschreibung', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier eine Bildbeschreibung ein.', verbose_name=b'Bildbeschreibung')),
                ('bildquelle', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier den Bildquelle ein. (privat, Kunde, Internet, BildDB)', max_length=256, verbose_name=b'Bildquelle')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
        migrations.CreateModel(
            name='Reisebilder',
            fields=[
                ('reisebildID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier einen optionalen Titel ein. (\xc3\x9cberschreibt Standard Bildtitel)', verbose_name=b'optionaler Titel')),
                ('zu_verwenden_in', models.CharField(blank=True, default=b'', help_text=b'Geben Sie an ob das Bild etwa im Katalog, Internet, Katalogvorstellung, Reisetagebuch, etc. ver\xc3\xb6ffentlicht werden soll. (kommaseparierte Liste)', max_length=256, verbose_name=b'Bild verwenden in ...')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Bilder bei der Darstellung', null=True, verbose_name=b'position')),
                ('bild_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Bild')),
                ('reise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise')),
            ],
            options={
                'verbose_name': 'Reisebild',
                'verbose_name_plural': 'Reisebilder',
            },
        ),
    ]
