# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 12:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0023_bild_reisebilder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reisetage',
            options={'ordering': ['tagnummer'], 'verbose_name': 'Reisetag', 'verbose_name_plural': 'Reisetage'},
        ),
        migrations.AlterField(
            model_name='reisetage',
            name='tagnummer',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name=b'Tagesnummer zum Ordnen'),
        ),
    ]
