# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0024_auto_20160127_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausflugspakete',
            options={'ordering': ['position'], 'verbose_name': 'Ausflugspaket', 'verbose_name_plural': 'Ausflugspakete'},
        ),
        migrations.AlterModelOptions(
            name='ausflugspaketezureisetagen',
            options={'ordering': ['position'], 'verbose_name': 'Zuordnung von Ausflugspaket zu Reisetag', 'verbose_name_plural': 'Zuordnung von Ausflugspaketen zu Reisetagen'},
        ),
        migrations.AlterModelOptions(
            name='ausflugspaketpreise',
            options={'ordering': ['position'], 'verbose_name': 'Ausflugspaketpreis', 'verbose_name_plural': 'Ausflugspaketpreise'},
        ),
        migrations.AlterModelOptions(
            name='fruehbucherrabatt',
            options={'ordering': ['position'], 'verbose_name': 'Fr\xfchbucherrabatt', 'verbose_name_plural': 'Fr\xfchbucherrabatte'},
        ),
        migrations.AlterModelOptions(
            name='leistungenausflugspaket',
            options={'ordering': ['position'], 'verbose_name': 'Leistung zum Ausflugspaket', 'verbose_name_plural': 'Leistungen zum Ausflugspaket'},
        ),
        migrations.AlterModelOptions(
            name='leistungenreise',
            options={'ordering': ['position'], 'verbose_name': 'Reiseleistung', 'verbose_name_plural': 'Reiseleistungen'},
        ),
        migrations.AlterModelOptions(
            name='reisebilder',
            options={'ordering': ['position'], 'verbose_name': 'Reisebild', 'verbose_name_plural': 'Reisebilder'},
        ),
        migrations.AlterModelOptions(
            name='reisehinweise',
            options={'ordering': ['position'], 'verbose_name': 'Reisehinweis', 'verbose_name_plural': 'Reisehinweise'},
        ),
        migrations.AlterModelOptions(
            name='reisekategorien',
            options={'ordering': ['position'], 'verbose_name': 'Reisekategorie', 'verbose_name_plural': 'Reisekategorien'},
        ),
        migrations.AlterModelOptions(
            name='reisepreise',
            options={'ordering': ['position'], 'verbose_name': 'Reisepreis', 'verbose_name_plural': 'Reisepreise'},
        ),
        migrations.AlterModelOptions(
            name='reisepreiszusatz',
            options={'ordering': ['position'], 'verbose_name': 'Preisdetail', 'verbose_name_plural': 'Preisdetails'},
        ),
        migrations.AlterModelOptions(
            name='reisetermine',
            options={'ordering': ['datum_beginn'], 'verbose_name': 'Reisetermin', 'verbose_name_plural': 'Reisetermine'},
        ),
        migrations.AlterModelOptions(
            name='reisezielregionen',
            options={'ordering': ['position'], 'verbose_name': 'Zielregion', 'verbose_name_plural': 'Zielregionen'},
        ),
        migrations.AlterModelOptions(
            name='zusatzleistung',
            options={'ordering': ['position'], 'verbose_name': 'Zusatzleistung', 'verbose_name_plural': 'Zusatzleistungen'},
        ),
        migrations.AddField(
            model_name='reise',
            name='status',
            field=models.CharField(choices=[(b'i', b'Idee'), (b'e', b'Entwurf'), (b'v', b'ver\xc3\xb6ffentlicht')], default=b'i', help_text=b'Hier den Status einer Reise w\xc3\xa4hlen.', max_length=1, verbose_name=b'Status einer Reise'),
        ),
        migrations.AlterField(
            model_name='leistungenreise',
            name='position',
            field=models.IntegerField(help_text=b'Position zur Sortierung', null=True, verbose_name=b'position'),
        ),
        migrations.AlterField(
            model_name='reisehinweise',
            name='position',
            field=models.IntegerField(help_text=b'Position zur Sortierung', null=True, verbose_name=b'position'),
        ),
    ]
