# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0025_auto_20160323_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='reise',
            name='welcher_katalog',
            field=models.CharField(null=True, blank=True, max_length=255, verbose_name='Welcher Katalog'),
        ),
    ]
