# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0026_reise_welcher_katalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('angebotID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('angebot', models.FileField(upload_to=b'angebote')),
                ('titel', models.CharField(blank=True, default=b'', help_text=b'Geben Sie hier den Titel des Angebots ein.', max_length=256, verbose_name=b'Angebottitel')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
            },
        ),
        migrations.CreateModel(
            name='Reiseangebote',
            fields=[
                ('reiseangebotID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.TextField(blank=True, default=b'', help_text=b'Geben Sie hier einen optionalen Titel ein. (\xc3\x9cberschreibt Standard Angebottitel)', verbose_name=b'optionaler Titel')),
                ('position', models.IntegerField(help_text=b'Position zur Bestimmung der Reihenfolge der Angebote bei der Darstellung', null=True, verbose_name=b'position')),
                ('angebot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Angebot')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'Reiseangebot',
                'verbose_name_plural': 'Reiseangebote',
            },
        ),
        migrations.AlterField(
            model_name='ausflugspaketezureisetagen',
            name='reisetag_id',
            field=models.ForeignKey(help_text=b'W\xc3\xa4hlen hier Sie die Zuordnung zu einem Reisetag.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Reisetage', verbose_name=b'Reisetag'),
        ),
        migrations.AlterField(
            model_name='reise',
            name='status',
            field=models.CharField(choices=[(b'i', b'Idee'), (b'e', b'Entwurf'), (b'f', b'fertiggestellt')], default=b'i', help_text=b'Hier den Status einer Reise w\xc3\xa4hlen.', max_length=1, verbose_name=b'Status der Reise'),
        ),
        migrations.AlterField(
            model_name='reise',
            name='welcher_katalog',
            field=models.CharField(choices=[(b'w', b'Winterkatalog'), (b's', b'Sommerkatalog'), (b'a', b'Winter- und Sommerkatalog'), (b'n', b'nicht zugeordnet')], default=b'n', help_text=b'Hier Katalog f\xc3\xbcr eine Reise w\xc3\xa4hlen.', max_length=1, verbose_name=b'Welcher Katalog?'),
        ),
        migrations.AlterField(
            model_name='reisehinweise',
            name='hinweis_id',
            field=models.ForeignKey(help_text=b'Suchen Sie hier einen Hinweistext aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Hinweis', verbose_name=b'Hinweis'),
        ),
        migrations.AlterField(
            model_name='reisekategorien',
            name='kategorie_id',
            field=models.ForeignKey(help_text=b'Suchen Sie hier eine Reisekategorie aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Kategorie', verbose_name=b'Reisekategorie'),
        ),
        migrations.AlterField(
            model_name='reisepreise',
            name='preis_id',
            field=models.ForeignKey(help_text=b'W\xc3\xa4hlen Sie hier die Art des Preises aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Preis', verbose_name=b'Bezeichnung Preis'),
        ),
        migrations.AlterField(
            model_name='reisepreiszusatz',
            name='preis_id',
            field=models.ForeignKey(help_text=b'W\xc3\xa4hlen Sie hier die Art des Preises aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Preis', verbose_name=b'Bezeichnung Preis'),
        ),
        migrations.AlterField(
            model_name='reisezielregionen',
            name='zielregion_id',
            field=models.ForeignKey(help_text=b'Suchen Sie hier eine Zielregion aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Zielregion', verbose_name=b'Zielregion'),
        ),
        migrations.AddField(
            model_name='reiseangebote',
            name='reise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reisen.Reise'),
        ),
    ]
