# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0026_reise_welcher_katalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausflugspaketezureisetagen',
            name='reisetag_id',
            field=models.ForeignKey(help_text=b'W\xc3\xa4hlen hier Sie die Zuordnung zu einem Reisetag.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Reisetage', verbose_name=b'Reisetag'),
        ),
        migrations.AlterField(
            model_name='reise',
            name='status',
            field=models.CharField(choices=[('i', 'Idee'), ('e', 'Entwurf'), ('f', 'fertiggestellt')], null=True, blank=True, max_length=1, verbose_name='Status einer Reise'),
        ),
        migrations.AlterField(
            model_name='reise',
            name='welcher_katalog',
            field=models.CharField(choices=[('w', 'Winterkatalog'), ('s', 'Sommerkatalog'), ('a', 'Winter- und Sommerkatalog'), ('n', 'nicht zugeordnet')], null=True, blank=True, max_length=1, verbose_name='Welcher Katalog?'),
        ),
        migrations.AlterField(
            model_name='reisehinweise',
            name='hinweis_id',
            field=models.ForeignKey(help_text=b'Suchen Sie hier einen Hinweistext aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Hinweis', verbose_name=b'Hinweis'),
        ),
        migrations.AlterField(
            model_name='reisekategorien',
            name='kategorie_id',
            field=models.ForeignKey(help_text=b'Suchen Sie hier eine Reisekategorie aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Kategorie', verbose_name=b'Reisekategorie'),
        ),
        migrations.AlterField(
            model_name='reisepreise',
            name='preis_id',
            field=models.ForeignKey(help_text=b'W\xc3\xa4hlen Sie hier die Art des Preises aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Preis', verbose_name=b'Bezeichnung Preis'),
        ),
        migrations.AlterField(
            model_name='reisepreiszusatz',
            name='preis_id',
            field=models.ForeignKey(help_text=b'W\xc3\xa4hlen Sie hier die Art des Preises aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Preis', verbose_name=b'Bezeichnung Preis'),
        ),
        migrations.AlterField(
            model_name='reisezielregionen',
            name='zielregion_id',
            field=models.ForeignKey(help_text=b'Suchen Sie hier eine Zielregion aus.', on_delete=django.db.models.deletion.CASCADE, to='reisen.Zielregion', verbose_name=b'Zielregion'),
        ),
    ]
