# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0027_auto_20160324_1218'),
        ('reisen', '0028_auto_20160324_1218'),
    ]

    operations = [
    ]
